function addToCart(productId) {
  // ...existing code...
  // alert('カートに追加しました');
  showToast('カートに追加しました', '<svg viewBox="0 0 24 24" width="20" height="20" fill="none"><circle cx="12" cy="12" r="10" stroke="#1976d2" stroke-width="2"/><path d="M8 12.5l2.5 2.5 5-5" stroke="#1976d2" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg>');
  // ...existing code...
}